-- ======================================================
-- 1. CLEANUP (Drop existing objects)
-- ======================================================
BEGIN
   FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN 
     ('ORDER_STATUS_HISTORY', 'PRICE_AUDIT_LOG', 'ORDER_ITEMS', 'ORDERS', 'PRODUCTS', 'BRANDS', 'USERS', 'CATEGORIES', 'USER_ROLES'))
   LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;

   FOR s IN (SELECT sequence_name FROM user_sequences WHERE sequence_name IN ('SEQ_ORDER_ID', 'ORDER_ITEM_SEQ', 'PROD_SEQ'))
   LOOP
      EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
   END LOOP;
END;
/

-- ======================================================
-- 2. LOOKUP TABLES
-- ======================================================
CREATE TABLE USER_ROLES (
    role_id NUMBER PRIMARY KEY,
    role_name VARCHAR2(20) NOT NULL UNIQUE
);

CREATE TABLE CATEGORIES (
    category_id NUMBER PRIMARY KEY,
    category_name VARCHAR2(50) NOT NULL,
    description VARCHAR2(255)
);

-- ======================================================
-- 3. CORE ENTITIES (USERS & BRANDS)
-- ======================================================
CREATE TABLE USERS (
    user_id NUMBER PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    password VARCHAR2(100) NOT NULL,
    role_id NUMBER REFERENCES USER_ROLES(role_id),
    created_at DATE DEFAULT SYSDATE,
    CONSTRAINT ck_user_email_format CHECK (email LIKE '%@%.%')
);

CREATE TABLE BRANDS (
    brand_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_name VARCHAR2(100) NOT NULL UNIQUE,
    owner_id NUMBER REFERENCES USERS(user_id), -- The Manager
    created_at DATE DEFAULT SYSDATE
);

-- ======================================================
-- 4. PRODUCT & TRANSACTION TABLES
-- ======================================================
CREATE TABLE PRODUCTS (
    product_id NUMBER PRIMARY KEY,
    product_name VARCHAR2(100) NOT NULL,
    price NUMBER(10,2) NOT NULL,
    stock_quantity NUMBER DEFAULT 0,
    category_id NUMBER REFERENCES CATEGORIES(category_id),
    brand_id NUMBER REFERENCES BRANDS(brand_id), -- Linked to the Brand
    CONSTRAINT ck_product_price CHECK (price > 0),
    CONSTRAINT ck_product_stock CHECK (stock_quantity >= 0)
);

CREATE TABLE ORDERS (
    order_id NUMBER PRIMARY KEY,
    user_id NUMBER REFERENCES USERS(user_id),
    order_date DATE DEFAULT SYSDATE,
    total_amount NUMBER(10,2) DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'Pending'
);

CREATE TABLE ORDER_ITEMS (
    order_item_id NUMBER PRIMARY KEY,
    order_id NUMBER REFERENCES ORDERS(order_id) ON DELETE CASCADE,
    product_id NUMBER REFERENCES PRODUCTS(product_id),
    quantity NUMBER NOT NULL,
    unit_price NUMBER(10,2) NOT NULL,
    CONSTRAINT ck_item_qty CHECK (quantity > 0)
);

-- ======================================================
-- 5. AUDIT & LOG TABLES
-- ======================================================
CREATE TABLE PRICE_AUDIT_LOG (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER REFERENCES PRODUCTS(product_id),
    old_price NUMBER(10,2),
    new_price NUMBER(10,2),
    changed_by NUMBER REFERENCES USERS(user_id),
    changed_at DATE DEFAULT SYSDATE
);

CREATE TABLE ORDER_STATUS_HISTORY (
    history_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER REFERENCES ORDERS(order_id),
    status_code VARCHAR2(20) NOT NULL,
    update_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ======================================================
-- 6. SEQUENCES & INDEXES
-- ======================================================
CREATE SEQUENCE seq_order_id START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE order_item_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE prod_seq START WITH 500 INCREMENT BY 1 NOCACHE;

CREATE INDEX idx_product_name ON PRODUCTS(product_name);
CREATE INDEX idx_order_status ON ORDERS(status);